import { Theme } from '@/types/theme';

export const nesTheme: Theme = {
  id: 'nes',
  name: 'NES Classic',
  type: 'pixel',
  cssVars: {
    '--background': '#fafafa',
    '--foreground': '#000000',
    '--primary': '#000000',
    '--primary-foreground': '#fafafa',
    '--destructive': '#e74c3c',
    '--destructive-foreground': '#ffffff',
    '--success': '#27ae60',
    '--success-foreground': '#ffffff',
    '--warning': '#f39c12',
    '--warning-foreground': '#000000',
    '--secondary': '#bdc3c7',
    '--secondary-foreground': '#000000',
    '--accent': '#ecf0f1',
    '--accent-foreground': '#000000',
    '--border': '#000000',
    '--input': '#ffffff',
    '--ring': '#3498db',
    '--radius': '0px',
  },
  components: {
    button: {
      base: 'font-pixel relative transition-colors focus-visible:outline-none disabled:opacity-50 items-center justify-center inline-flex',
      variants: {
        default: 'bg-[#bdc3c7] text-black hover:bg-[#95a5a6]',
        primary: 'bg-[#3498db] text-white hover:bg-[#2980b9]',
        destructive: 'bg-[#e74c3c] text-white hover:bg-[#c0392b]',
        success: 'bg-[#27ae60] text-white hover:bg-[#229954]',
        warning: 'bg-[#f39c12] text-black hover:bg-[#e67e22]',
        outline: 'bg-white text-black hover:bg-[#ecf0f1] border-2 border-black',
        secondary: 'bg-[#95a5a6] text-black hover:bg-[#7f8c8d]',
        ghost: 'bg-transparent text-black hover:bg-[#ecf0f1]',
        link: 'bg-transparent text-[#3498db] hover:underline',
      },
      sizes: {
        sm: 'text-xs px-2 py-1 min-h-[24px]',
        default: 'text-sm px-3 py-1 min-h-[32px]',
        lg: 'text-base px-4 py-2 min-h-[40px]',
        icon: 'w-8 h-8 p-1',
      },
      shadows: {
        default: '#95a5a6',
        primary: '#2980b9',
        destructive: '#c0392b',
        success: '#229954',
        warning: '#e67e22',
        outline: '#e0e0e0',
        secondary: '#7f8c8d',
        ghost: '#e0e0e0',
        link: '#2980b9',
      },
      border: {
        size: 4,
        cutCorners: true,
      },
    },
    input: {
      base: 'font-pixel transition-colors disabled:cursor-not-allowed disabled:opacity-50',
      backgroundColor: '#ffffff',
      variants: {
        default: 'bg-[#bdc3c7] text-black placeholder:text-gray-700',
        primary: 'bg-[#3498db] text-white placeholder:text-blue-100',
        destructive: 'bg-[#e74c3c] text-white placeholder:text-red-100',
        outline: 'bg-[#ffffff] text-black placeholder:text-gray-500',
        secondary: 'bg-[#95a5a6] text-black placeholder:text-gray-700',
        ghost: 'bg-transparent text-black placeholder:text-gray-500',
        success: 'bg-[#27ae60] text-white placeholder:text-green-100',
        warning: 'bg-[#f39c12] text-black placeholder:text-yellow-700',
        filled: 'bg-[#95a5a6] text-white placeholder:text-gray-200',
      },
      sizes: {
        sm: 'text-xs px-2 py-1 min-h-[24px]',
        default: 'text-sm px-3 py-2 min-h-[32px]',
        lg: 'text-base px-4 py-3 min-h-[40px]',
        xl: 'text-lg px-6 py-4 min-h-[48px]',
      },
      border: {
        size: 4,
        cutCorners: true,
      },
    },
    card: {
      base: 'font-pixel py-6',
      variants: {
        default: 'bg-[#bdc3c7] text-black',
        primary: 'bg-[#3498db] text-white',
        destructive: 'bg-[#e74c3c] text-white',
        outline: 'bg-[#ffffff] text-black',
        secondary: 'bg-[#95a5a6] text-black',
        ghost: 'bg-transparent text-black',
      },
      border: {
        size: 4,
        cutCorners: true,
      },
    },
    select: {
      base: 'font-pixel transition-colors disabled:cursor-not-allowed disabled:opacity-50',
      variants: {
        default: 'bg-[#bdc3c7] text-black hover:bg-[#95a5a6]',
        primary: 'bg-[#3498db] text-white hover:bg-[#2980b9]',
        destructive: 'bg-[#e74c3c] text-white hover:bg-[#c0392b]',
        outline: 'bg-[#ffffff] text-black hover:bg-[#ecf0f1]',
        secondary: 'bg-[#95a5a6] text-black hover:bg-[#7f8c8d]',
        ghost: 'bg-transparent text-black hover:bg-[#ecf0f1]',
        success: 'bg-[#27ae60] text-white hover:bg-[#229954]',
        warning: 'bg-[#f39c12] text-black hover:bg-[#e67e22]',
      },
      sizes: {
        sm: 'text-xs px-2 py-1 min-h-[24px]',
        default: 'text-sm px-3 py-2 min-h-[32px]',
        lg: 'text-base px-4 py-3 min-h-[40px]',
      },
      border: {
        size: 4,
        cutCorners: true,
      },
    },
  },
}