export const EXPRESS_SERVER_URL = import.meta.env.VITE_EXPRESS_API_URL
export const EXPRESS_SERVER_API_PORT = import.meta.env.VITE_EXPRESS_API_PORT
export const EXPRESS_SERVER_URL_WITH_PORT = `${EXPRESS_SERVER_URL}:${EXPRESS_SERVER_API_PORT}`